In [2]:
import numpy as np
import librosa
import tensorflow as tf
import numpy as np
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, LSTM
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [4]:
Y, sr = librosa.load('/content/gdrive/My Drive/ru_data/icemarch/icemarch_0001.wav')
loaded_sound_1 =  np.array((librosa.feature.mfcc(Y, sr=sr, S=None, n_mfcc=20)))


In [5]:
loaded_sound_1

array([[-6.29850436e+02, -6.28280370e+02, -6.28404551e+02, ...,
        -6.39005714e+02, -6.39005714e+02, -6.39005714e+02],
       [-1.17727861e+00, -8.83244547e-01, -1.25705553e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.01739918e+01, -1.24431884e+01, -1.28665308e+01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 2.40732906e+00,  2.72969223e+00,  4.03071263e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.57920358e+00,  1.00026874e+01,  1.05157440e+01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.95568602e+00, -3.00618839e+00, -4.16553146e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [6]:
Y, sr = librosa.load('/content/gdrive/My Drive/ru_data/icemarch/icemarch_0002.wav')
loaded_sound_2 = np.array((librosa.feature.mfcc(Y, sr=sr, S=None, n_mfcc=20)), ndmin= 3)

In [7]:
loaded_sound_2

array([[[-6.63832862e+02, -6.63832862e+02, -6.63832862e+02, ...,
         -6.63832862e+02, -6.62466206e+02, -6.35300397e+02],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00, -8.41531824e-01, -1.53585979e+01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00, -7.82618274e-01, -1.01441273e+01],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00, -5.28596967e-01, -4.07689900e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  1.14477596e+00,  4.38128320e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00, -7.61135063e-02,  4.42990420e+00]]])

In [8]:
type(loaded_sound_2[0][0])

numpy.ndarray

In [9]:
loaded_sound_2.shape

(1, 20, 407)

In [10]:
Y, sr = librosa.load('/content/gdrive/My Drive/ru_data/icemarch/icemarch_0003.wav')
loaded_sound_3 = np.array(((librosa.feature.mfcc(Y, sr=sr))))

In [11]:
loaded_sound_3

array([[-5.28921772e+02, -4.92083552e+02, -4.52276971e+02, ...,
        -6.31423134e+02, -6.30241276e+02, -6.30709332e+02],
       [-3.85633769e+01, -5.12620742e+01, -5.53359874e+01, ...,
         4.95763625e-01,  6.09557743e-01,  3.84437402e-01],
       [-3.80098419e+01, -4.89200838e+01, -6.34206367e+01, ...,
        -1.64483085e+00, -3.49760674e+00, -2.93886093e+00],
       ...,
       [-1.03767838e+01, -1.48231507e+01, -1.31106106e+01, ...,
        -1.91464850e+00, -2.79973319e+00, -2.44698615e+00],
       [ 6.56818530e+00,  6.73937817e+00,  1.09909053e+01, ...,
         1.03611582e-01,  2.29377843e-01, -2.13153541e-01],
       [-6.50014169e+00, -1.16150485e+00,  1.45602323e+00, ...,
         1.80563390e+00,  3.14126552e+00,  2.71403709e+00]])

In [12]:
type(loaded_sound_2)

numpy.ndarray

In [13]:
y = 'книгу посвящаю горячо любимой матери часть первая с фронта до ростова'

In [14]:
y

'книгу посвящаю горячо любимой матери часть первая с фронта до ростова'

In [15]:
vocabulary = { 'а': 1,
               'б': 2,
               'в': 3,
               'г': 4,
               'д': 5,
               'е': 6,
               'ё': 7,
               'ж': 8,
               'з': 9,
               'и': 10,
               'й': 11,
               'к': 12,
               'л': 13,
               'м': 14,
               'н': 15,
               'о': 16,
               'п': 17,
               'р': 18,
               'с': 19,
               'т': 20,
               'у': 21,
               'ф': 22,
               'х': 23,
               'ц': 24,
               'ч': 25,
               'ш': 26,
               'щ': 27,
               'ъ': 28,
               'ы': 29,
               'ь': 30,
               'э': 31,
               'ю': 32,
               'я': 33,
               ' ': 34}

inv_mapping = dict(zip(vocabulary.values(), vocabulary.keys()))


In [16]:
tr = []

In [17]:
for elem in y:
  number = vocabulary[elem]
  tr.append(number)
print(tr)

[12, 15, 10, 4, 21, 34, 17, 16, 19, 3, 33, 27, 1, 32, 34, 4, 16, 18, 33, 25, 16, 34, 13, 32, 2, 10, 14, 16, 11, 34, 14, 1, 20, 6, 18, 10, 34, 25, 1, 19, 20, 30, 34, 17, 6, 18, 3, 1, 33, 34, 19, 34, 22, 18, 16, 15, 20, 1, 34, 5, 16, 34, 18, 16, 19, 20, 16, 3, 1]


In [18]:
tr = np.array(np.array(tr), ndmin= 2)

In [19]:
loaded_sound_2.shape

(1, 20, 407)

In [20]:
tr.shape


(1, 69)

In [21]:
len(tr)

1

In [22]:
model = Sequential()

model.add(LSTM(units=512, batch_input_shape = (1,20,407),  return_sequences=True))
model.add(LSTM(units=256,return_sequences=True))
model.add(LSTM(units=128,return_sequences=True))
model.add(LSTM(units=69))
model.add(Dense(units=69, activation='relu'))
model.add(Dense(units=69, activation= 'relu'))
model.add(Dense(units=69, activation='softmax'))


model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])



In [23]:
for layer in model.layers:
    print(layer.output_shape)

(1, 20, 512)
(1, 20, 256)
(1, 20, 128)
(1, 69)
(1, 69)
(1, 69)


In [24]:
model.fit(loaded_sound_2, tr, epochs= 100)
model.summary()

Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 5207.0576 - accuracy: 0.0000e+00
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 5211.1685 - accuracy: 0.0000e+00
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 5248.1450 - accuracy: 0.0000e+00
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 5272.6196 - accuracy: 0.0000e+00
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 5293.0112 - accuracy: 0.0000e+00
Epoch 6/100
1/1 [==============================] - 0s 1ms/step - loss: 5321.5493 - accuracy: 0.0000e+00
Epoch 7/100
1/1 [==============================] - 0s 1ms/step - loss: 5356.8809 - accuracy: 0.0000e+00
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 5401.3228 - accuracy: 0.0000e+00
Epoch 9/100
1/1 [==============================] - 0s 1ms/step - loss: 5450.9468 - accuracy: 0.0000e+00
Epoch 10/100
1/1 [==============================] - 0s 2ms/step 

In [25]:
model.predict(loaded_sound_2)

array([[1.97416288e-08, 1.49857784e-02, 1.15883751e-02, 1.29294676e-06,
        1.17487316e-05, 1.86414234e-02, 7.23465753e-04, 1.29299405e-09,
        8.10053450e-07, 8.29308818e-04, 3.26784537e-08, 4.38750980e-10,
        1.13377885e-08, 7.61266332e-04, 8.68543069e-08, 5.86283910e-08,
        6.74845342e-06, 2.75652013e-07, 1.70143323e-07, 5.63867190e-14,
        9.77322969e-08, 3.14373665e-07, 1.21667526e-05, 1.27699878e-10,
        1.13481586e-03, 1.31421416e-07, 8.03442202e-09, 1.52888063e-10,
        1.56355425e-04, 1.85717379e-08, 7.29629319e-05, 3.83901388e-05,
        2.07067989e-02, 1.60345022e-04, 6.99315115e-06, 4.31882063e-06,
        2.28655463e-05, 1.34672504e-07, 1.33266271e-12, 1.23325549e-03,
        7.38531307e-05, 2.46151738e-10, 4.28356742e-03, 4.17708382e-02,
        3.81128993e-05, 5.34156803e-04, 9.80292407e-06, 9.66649259e-06,
        6.80717421e-05, 1.23812833e-05, 5.90516984e-01, 1.09892768e-04,
        2.88929105e-01, 1.05998458e-06, 4.08098322e-06, 2.098524